### PR TITLE
Upgrades: Python 3.7, Celery 4.3, Django 2.2

### PR DESCRIPTION
**Pull request by rstorey**
- [x] Pending GA release of celery 4.3.0 (remove `allow_preleases=True`)

- [x] Test/Upgrade django-celery-beat

- [x] Test removing the `CONN_MAX_AGE=0` setting for celery (restore to 15 minutes)

- [x] Django upgrade to 2.2 - pending https://github.com/cfpb/django-flags/pull/34

### CODE REVIEW

**Comment by acdha** [comment]
Looks like the release just happened: https://github.com/celery/celery/issues/5180#event-2241620919

**Comment by acdha** [comment]
This should be ready to test on ECS now

**Comment by acdha** [comment]
Since [Django 2.2 was released today](https://docs.djangoproject.com/en/2.2/releases/2.2/) I was going to test the upgrade but that currently doesn't work well since `django-flags` has a version pin `Django>=1.11,<2.2`. I opened https://github.com/cfpb/django-flags/pull/34 to track that.

**Comment by acdha** [comment]
Since @willbarton was kind enough to run https://github.com/cfpb/django-flags/pull/34 around so quickly this includes Django 2.2. We may want to look into some of the new features such as `bulk_update()` for the difficulty values.

**Comment by rstorey** [comment]
> 🎉How long do we want to test this before saying Celery is fixed?

I tested the importer, and celery beat seems to be fine. So I'm fine with merging this to master already.

**Pull request merged**
