### PR TITLE
Update status model

### PR DESCRIPTION
**Pull request by acdha**
This commit removes the old status fields from the models which don't directly track the status and adds validation to the transitions using several new fields to track key decisions and the user who made them.

See #222

### CODE REVIEW

**Comment by acdha** [comment]
@rstorey The major parts of this are done. The main thing which is left is updating the various places which filter on status values and measuring the performance impact to decide whether or not we need to cache the asset transcription status values or add some indexes (likely).

**Comment by acdha** [comment]
@rstorey I updated the migration as part of adding a rollup transcription status field to Assets to reduce the complexity of the queries in the item detail view.

**Comment by rstorey** [comment]
The migrations are working now, but travis is complaining.

**Comment by acdha** [comment]
Yeah, there are some tests I haven't updated yet since the actual code is working correctly

**Comment by acdha** [comment]
As of the last commits, there are tests covering the basic functionality and most of the branches. If you want to merge, that's fine by me.

**Pull request merged**
