### PR TITLE
Database-backed static pages

### LINKED ISSUE #616: Be able to make edits to static content w/out creating a release version
Community managers often need to make edits to static pages to correct typos, refine guides or add a update to the latest page. We need a solution that by passes the regular PR process similar to campaign content.

### PR DESCRIPTION
**Pull request by acdha**
This is based on #203 to avoid needing to move more code around. It should close #616:

* [x] Admins can update static page content
* [x] Live preview of generated HTML
* [x] Breadcrumb navigation follows the previous logic for path to title generation

The current static page content is included as a fixture.

Left unattempted is any way to move content from dev/test/staging to production — copy and paste works and preserves the admin change history.

### CODE REVIEW

**Comment by acdha** [comment]
This is ready for review now that it has a decent code editor to go with the preview & the tests are updated

**Comment by acdha** [comment]
@elainekamlley Do you want to do any other review before merging this feature?

**Comment by elainekamlley** [comment]
@acdha Nope, we'll test this feature in staging

**Comment by acdha** [comment]
Good. Note that we need to either load the static page fixture or copy-and-paste the existing markdown content on each database cluster – for safety it doesn't do that automatically since that would overwrite your edits.

**Pull request merged**
