### PR TITLE
Split asset_detail.html template into smaller templates. Re-added a JS function that was needed.

### PR DESCRIPTION
**Pull request by joshuastegmaier**
https://staff.loc.gov/tasks/browse/CONCD-896

### CODE REVIEW

**Review by rasarkar — APPROVED** [review]
Somewhat related: we should probably rename quick_tips_modal to campaign_tips_modal.

**Comment by joshuastegmaier** [comment]
I actually decided against doing that since quick tips is used elsewhere. We can continue using that name in the code for the feature.

**Comment by jkueloc** [comment]
@joshuastegmaier This is still marked as a draft...?

**Comment by joshuastegmaier** [comment]
Just didn't hit the button when the checks all finished. Sorry!

**Pull request merged**
