### PR TITLE
Allow admins to set the path for new simple pages

### PR DESCRIPTION
**Pull request by rstorey**
This bug fix will allow you to be able to set the path for the new resources page.

### CODE REVIEW

**Comment by acdha** [comment]
Since we're reversing part of the decision about the simple pages’ design, do we want to go further by adding validation for the path values (either to prevent conflicts or to ensure that the route exists first), or to add this as a 404 handler so new paths can be added any time they don't conflict?

**Comment by rstorey** [comment]
I'm not clear on what's being reversed here. How are admins supposed to create new simple pages with the path set to read only?

**Comment by acdha** [comment]
When we added the simple page feature, I had asked about the ability to add new pages and it was agreed that this would not be allowed — only the existing static pages would be available. Since we're changing that decision we probably also want to update the UI around the paths to avoid confusion.

**Comment by rstorey** [comment]
Ahhhhh. Yup, changing that decision. I will ticket this for a future sprint.

**Pull request merged**
