### PR TITLE
Continued progress indicator work

### PR DESCRIPTION
**Pull request by acdha**
* Adjust progress bar colors and ordering
* Adjust sizes for progress bars on cards
* Display the contributor count above the progress bar
* Bring the campaign detail page's project list inline with the lower-level listings
* Display progress bars on the project and campaign pages

See #626
See #566

### CODE REVIEW

**Comment by acdha** [comment]
Campaign detail page:

screen shot 2018-11-15 at 11 14 12


Project detail page:

screen shot 2018-11-15 at 11 13 45


Item detail page:

screen shot 2018-11-15 at 11 14 02

**Comment by rstorey** [comment]
Not crazy about the black border around the progress bar in the cards... is there an alternative to that? It especially looks weird since the cards themselves have a much lighter border.

**Comment by acdha** [comment]
@rstorey that matches the comps. We can tone it down to one of the border colors we're using elsewhere in the UI (e.g. bg-medium-gray or bg-dark-gray) or just get rid of it entirely — feel free to play with the value in the developer tools and see how it feels.

**Comment by rstorey** [comment]
I like it best with no border around the progress bar: 
screen shot 2018-11-15 at 11 43 00 am

**Comment by colefemeno** [comment]
@acdha @rstorey this is looking good! 
Can we also apply the de-emphasizing gray (#626 ) on the Project detail page to an item if it is complete? So all of these would be de-emphasized 
projectdetail_itemscompletenotgray_20181115

**Comment by rstorey** [comment]
From @colefemeno : let's add "Not Started" - and if not too difficult, change "Open for Edit" to "In Progress"

**Comment by acdha** [comment]
@colefemeno The CSS to make entirely completed things is already present on the project and campaign detail pages but we need to update the source of that data after the status change updates.

**Pull request merged**
