### PR TITLE
Added pip-audit Github workflow

### PR DESCRIPTION
**Pull request by joshuastegmaier**

### CODE REVIEW

**Comment by joshuastegmaier** [comment]
This request is for testing workflows; should not be merged.

**Comment by jkueloc** [comment]
master s/b main

**Comment by joshuastegmaier** [comment]
Ah, I copied that part from the codeql workflow and didn't notice!

**Comment by jkueloc** [comment]
yeah - I have a ticket to fix it - but didn't necessarily want to incur the cost of it running more frequently.

**Pull request closed without merging**
