### PR TITLE
Add beta label to logo

### LINKED ISSUE #367: Add beta to logo
As a user, I want to see a banner at the top of the screen that lets me know that this site is beta

### PR DESCRIPTION
**Pull request by acdha**
image

Closes #367

### CODE REVIEW

**Comment by rstorey** [comment]
Should the "Crowd" in the header be plain HTML or an image? I uploaded the image I got from Jamie to the ticket. In either case, I think the underline on hover (over "crowd") looks really bad.

**Comment by jbresner** [comment]
We've been treating these as graphics (Catalog, Staff Intranet, Research Guides) when it's a sub-brand. We don't have a hover state for the logo or sub brand portion of the logo so yeah, no underline would be preferred.

**Comment by rstorey** [comment]
I have an SVG but I can't upload one of those to GitHub.

**Comment by jbresner** [comment]
I'm attaching the LOC logo and the Crowd sub-brand lockup as separate SVG files (compressed because GitHub doesn't like SVG). The vertical rule will have to be added with CSS, similar to what we did on the Staff Intranet home page.

[logos.zip](https://github.com/LibraryOfCongress/concordia/files/2485035/logos.zip)

**Pull request merged**
