### PR TITLE
Transcription View: avoid updates for unmodified sources

### PR DESCRIPTION
**Pull request by acdha**
This avoids the problem in #949 where the update triggered by the reservation system would cause
the transcription view to replace any unsaved text with the original starting text. Now the update
method will not replace the text when the upstream value has not changed.

* [x] Confirm that text changes are not replaced by the reservation renewal updates
* [x] Confirm that updates made by another user are reflected when the reservation is eventually obtained
* [x] Confirm that unavailable assets will be retried 
* [ ] Confirm that the UI does not unlock before it has been updated to the latest transcription made by someone else

### CODE REVIEW

**Comment by rstorey** [comment]
Looks good so far.

**Comment by acdha** [comment]
I'm heading out for the day; this definitely needs more testing for the sequencing around reservation races

**Comment by rstorey** [comment]
I did a bit of testing in Chrome: It seems like when an asset is first opened, the reserve asset call doesn't work - there's a message in the console about reserve asset being called without an open asset. The subsequent reservation calls do work okay.

**Comment by acdha** [comment]
That one was working correctly, too, but the log message was now being called in situations where it previously couldn't be. 6203cade700c36ed1f6b498b1b9ed35735206b75 and 698127394fc7959d3958dca3a82bd3eeff731370 improve the logging.

**Comment by acdha** [comment]
@klee72 would it be useful to cherry-pick https://github.com/LibraryOfCongress/concordia/pull/964/commits/ca434876a1ae68e4b3c8fb7f8aa9f697ffae7231 and https://github.com/LibraryOfCongress/concordia/pull/964/commits/eb114700f8fe983442c02992a9774d788924c1c3 into a separate branch for independent review/refinement?

**Comment by acdha** [comment]
I think it's probably time to review and merge this with a known caveat: the “most recently updated” sort isn't stable and so there's an annoying jump when you accept a translation because it bumps the item to the bottom of the list, triggering an on-demand load, which triggers another update. That can be improved in another branch, however.

**Comment by rstorey** [comment]
Looks like the issue in #949 is still occurring in crowd-dev.

**Comment by acdha** [comment]
That doesn't reproduce in Chrome or Firefox. Is it possible that the test system hadn't picked up the new code yet? It might be easiest to check by opening the dev tools and confirming that line 634 of components.js looks like this: 

https://github.com/LibraryOfCongress/concordia/blob/80124c768bc43ade9831b6af2060b45f8b00fceb/concordia/static/js/action-app/components.js#L634

**Comment by rstorey** [comment]
I just reproduced it in chrome on crowd-dev and confirmed that the line you quoted is in components.js on line 658. It occurs both with not started and in progress transcriptions. Crowd-dev is at version 2f813f18 which is the latest version of the code.

**Comment by rstorey** [comment]
I also reproduced in Firefox. I can make a video if you really need it.

**Comment by acdha** [comment]
Reproducing this turns out to depend on what assets you're looking at. It does not affect any asset with at least some progress but the test in https://github.com/LibraryOfCongress/concordia/blob/80124c768bc43ade9831b6af2060b45f8b00fceb/concordia/static/js/action-app/components.js#L626 needs to handle the case where no transcription exists at all.

**Pull request merged**
