### PR TITLE
WIP: Unified transcription status filtering UI

### PR DESCRIPTION
**Pull request by acdha**
This changes the transcription status filter to be a group of radio-style buttons on the campaign, project, and item detail pages.

Campaign detail:

image

Project detail:

image

Item detail:

image

### CODE REVIEW

**Comment by acdha** [comment]
Yeah, I like the numbers, too, so I'm trying a few variations like this:

image

**Comment by rstorey** [comment]
Can the image count / page count be part of the tooltip for the progress bar sections?

**Comment by rstorey** [comment]
Or maybe the whole table with the numbers is a giant fancy tooltip over the entire progress bar.

**Comment by acdha** [comment]
We can definitely add them as a tooltip. I'm also wondering about returning them to the buttons since a horizontal layout gives us the room needed:

image

**Comment by rstorey** [comment]
I really like the side-by-side layout with the filter buttons / legend to the left and the progress bar to the right. And I think you're right about how much vertical space it takes up. I think personally I would prefer to keep the table intact and display it in a popover thingie?

**Comment by acdha** [comment]
I was just testing `<details>`:

image
image

**Comment by rstorey** [comment]
I vote for that one.

**Comment by acdha** [comment]
I was wondering about simply making it hidden / zero height until either a click or hover on the progress bar expands it.

**Comment by acdha** [comment]
I think `<details>` may have MS Edge / IE 11 issues so we probably want this to be custom. Sigh…

**Comment by rstorey** [comment]
Can we use the same popover we used on the asset detail page for the nothing to transcribe help?

**Comment by acdha** [comment]
Using the popover looks like this:

screenshot 2018-11-15 16 00 23

**Pull request merged**
