### PR TITLE
Add memorial day challenge carousel slide based on release branch 

### PR DESCRIPTION
**Pull request by rstorey**
With feature flag.

Note: when deploying this release, the NEW_CAROUSEL_SLIDE flag needs to switch from on to off (switch from True to False).

This PR contains the same changes as in #972  but this one is based on the release branch.

### CODE REVIEW

**Comment by elainekamlley** [comment]
Yes, we discussed in a programming meeting to remove Jump In while Bourne Challenge is up for a week. As for the images, is Whitman the only image that is different?

**Comment by acdha** [comment]
> Yes, we discussed in a programming meeting to remove Jump In while Bourne Challenge is up for a week

Good, that wasn't clear from the original issue

>  As for the images, is Whitman the only image that is different?

Yes — the older ones are all 1200x480, but Whitman is 1197x480 and the new one is 1199x558:

```
concordia/static/img/homepage-carousel/crowd-home.jpg JPEG 1200x480 1200x480+0+0 8-bit sRGB 131730B 0.000u 0:00.001
concordia/static/img/homepage-carousel/mem-day-challenge.jpg JPEG 1199x558 1199x558+0+0 8-bit sRGB 83158B 0.000u 0:00.000
concordia/static/img/homepage-carousel/review.jpg JPEG 1200x480 1200x480+0+0 8-bit sRGB 55188B 0.000u 0:00.000
concordia/static/img/homepage-carousel/welcome-guide.jpg JPEG 1200x480 1200x480+0+0 8-bit sRGB 81159B 0.000u 0:00.000
concordia/static/img/homepage-carousel/whitman.jpg JPEG 1197x480 1197x480+0+0 8-bit sRGB 72105B 0.000u 0:00.002
```

**Comment by elainekamlley** [comment]
Oye vey, I'll get correct image sizes for Whitman and memorial day challenge. Hold tight.

**Comment by acdha** [comment]
With the optimized images we no longer have the carousel bounce. Staging should be updated for review soon.

**Pull request merged**
