### PR TITLE
Update homepage carousel

### PR DESCRIPTION
**Pull request by acdha**
This is collecting the changes from #550:

* [x] pause rotation when the pointer is over the carousel
* [x] add navigation arrows
* [x] add carousel indicators
* [x] add new carousel images
* [x] add new carousel text & link targets
* [x] Adjust spacing for the text box to match [@jbresner's comps](https://github.com/LibraryOfCongress/concordia/issues/550#issuecomment-439121557)

### CODE REVIEW

**Comment by acdha** [comment]
Here's an example screenshot of the current design, which is basically Bootstrap with larger navigation arrows:

image
image
image

We probably need to think about something like a box-shadow to make the arrows and indicators more consistently visible across a range of background colors, especially since they're white and our default homepage image has lots of the same color.

**Comment by acdha** [comment]
Here's what it looks like with the latest commits:

image

image

image

I adjusted some of the spacing slightly from @jbresner's comps to ensure that the text always fits and that the overlay is always distinct from the carousel navigation buttons.

**Comment by acdha** [comment]
One other question, which could be deferred along with updating the alt text: do we ever want the button text to be something other than “LET's GO”?

**Comment by elainekamlley** [comment]
@acdha I think so eventually. For the Welcome Guide I think `Learn more` would be more appropriate

**Comment by acdha** [comment]
@elainekamlley let's put a ticket in the next sprint. It'll be easy to add but I don't want to add another review cycle here.

**Pull request merged**
